name = "RsHtml"
grammar = "rshtml"
path_suffixes = ["rs.html"]

autoclose_before = ">})"
block_comment = { start = "@*", prefix = "", end = "*@", tab_size = 0 }
wrap_characters = { start_prefix = "<", start_suffix = ">", end_prefix = "</", end_suffix = ">" }
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = [
    "comment",
    "string",
  ] },
  { start = "<", end = ">", close = false, newline = true, not_in = [
    "comment",
    "string",
  ] },
  { start = "!--", end = " --", close = true, newline = false, not_in = [
    "comment",
    "string",
  ] },

  { start = "@*", end = "*@", close = true, newline = false },
]
completion_query_characters = ["-"]
